[features]
seeds = false
skip-lint = false

[programs.devnet]
morra_program = "FYG1SQaM49FGPQEGco8s9x4i3MzquotS48XcNre1UMBf"

[programs.localnet]
morra_program = "FYG1SQaM49FGPQEGco8s9x4i3MzquotS48XcNre1UMBf"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/"

[toolchain]
anchor_version = "0.31.0"
solana_version = "1.17.0"
